# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: "Techlore"
title: "Techlore | Digital Rights for All"
tagline: "Digital Rights for All"
email: contact@techlore.tech
description: >- # this means to ignore newlines until "twitter:"
  Techlore is educating people about digital rights, privacy, security,
  digital control, and other important topics to push the world towards a safer internet.
twitter: "TechloreInc"
mastodon:
  username: "techlore"
  server: "social.lol"
ogImages:
  default:      "/assets/images/og-image-1200x630-default.png"
  about:        "/assets/images/og-image-1200x630-about.png"
  goincognito:  "/assets/images/og-image-1200x630-goincognito.png"
  resources:    "/assets/images/og-image-1200x630-resources.png"
  spa:          "/assets/images/og-image-1200x630-spa.png"
  support:      "/assets/images/og-image-1200x630-support.png"
  videos:       "/assets/images/og-image-1200x630-videos.png"
  vpn:          "/assets/images/og-image-1200x630-vpn.png"
url: "https://www.techlore.tech"

# -----------------------------------------
# Global links
#
forumJson: "https://discuss.techlore.tech/top.json?period=weekly" # only used in production environment
techloreWeb:
  links:
    github: "https://github.com/techlore/website"
techloreVideos:
  links:
    peertube: "https://techlore.tv/c/techlore/videos?sort=-originallyPublishedAt"
    youtube: "https://www.youtube.com/@techlore"
  extra:
    odysee: "https://odysee.com/@techlore:3"
    tiktok: "https://www.tiktok.com/@techlore"
    learning: "https://learn.techlore.tech/"
    teachable: "https://techlore.teachable.com/"
techloreClips:
  links:
    youtube: "https://www.youtube.com/@techloreclips"
surveillanceReport:
  links:
    web: "https://www.surveillancereport.tech/"
    rss: "https://feeds.acast.com/public/shows/65e15188b8456c00169f4864"
    peertube: "https://apertatube.net/c/surveillancereport/videos"
    youtube: "https://www.youtube.com/@SurveillanceReport"
goincognito:
  links:
    premium: "https://techlore.teachable.com/p/go-incognito"
support:
  links: # these links also appear in the "feature box" on the homepage
    techlorian: "https://discuss.techlore.tech/s"
    patreon: "https://www.patreon.com/techlore"
    paypal: "https://www.paypal.com/donate?hosted_button_id=B3GU7WNGBGQ4J"
    xmrchat: "https://xmrchat.com/techlore"
  extra:
    youtube: "https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg/join"
    githubSponsors: "https://github.com/sponsors/techlore"
    sponsors: "https://discuss.techlore.tech/pub/sponsors"
socials:
  links: # these links also appear in the "feature box" on the homepage amd in the footer
    youtube: "https://www.youtube.com/@techlore"
    mastodon: "https://social.lol/@techlore"
    rss: "/rss"
    signal: "https://discuss.techlore.tech/t/signal-usernames-are-here-join-our-exclusive-signal-group/7640"
    twitter: "https://twitter.com/TechloreInc"
    bluesky: "https://bsky.app/profile/techlore.tech"
    telegram: "https://t.me/techlorefeed"
    matrix: "https://matrix.to/#/%23techlore:matrix.org"
  extra:
    linkedin: "https://www.linkedin.com/company/techloreinc/"
forum:
  links:
    discuss: "https://discuss.techlore.tech/"
plexus:
  links:
    web: "https://plexus.techlore.tech/"
    app: "https://github.com/techlore/Plexus-app?tab=readme-ov-file#download"
inactive:
  links:
    omglol: "https://techlore.omg.lol/"
    spring: "https://shop.techlore.tech/"
    kofi: "https://ko-fi.com/techlore"
    liberapay: "https://liberapay.com/Techlore/"
coaching:
  links:
    survey: "https://blocksurvey.io/techlore-coaching-application-08xcPirXSDehoCmJy0J5Cw?v=l"
wiki:
  links:
    wikidata: "https://www.wikidata.org/wiki/Q117304783"

xmrAddress: "49H4jTvUY5zaX8qLpVBstJFR7ayTMxxU3UyWpGqUoBM4UzM2zwUHA2sJ9i3AhQYdaqhFmS8PDfWKn1Tea4SKU6haMTXG8qD"
usdomain: "techlore.xmr"
openalias: "crypto@techlore.tech"

# -----------------------------------------
# Plugin settings
#
plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: development

# -----------------------------------------
# Collection settings
#
collections:
  guides:
    output: true
    permalink: /guides/:name
collections_dir: videos

# -----------------------------------------
# Archive settings
#
archive:
  itemsToShow: 15

# -----------------------------------------
# Sitemap configuration
#
defaults:
  -
    scope:
      path: ""
      type: "clips"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "surveillance-report"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "techlore"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "guides"
    values:
      sitemap: false

include:
  - _redirects
  - _headers

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
