# KNOWLEDGE BASE (Resources --> Applications) -----------------------------------------
# Data structure:
#     - name (string)
#     - desc (string)
#     - tags (array of strings):        contains misc info, eg. rendering engine, FOSS or proprietary, etc.
#     - affil (string, optional):       affiliate link
#     - labels:                         links to the official web (web), YouTube channel (youtube)
#                                       or anything for which there is an icon in `assets/icons/` (eg. github);
#                                       see "_data/_en/content.yml --> resources --> knowledgebase --> labels"
#     - color (string, optional):       color of the icon background (preferably in HEX format - #BADA55)
#     - favorite (boolean, optional):   marks a favorite and show a "star" icon next to the name
#
# Related:
#     Section (currently "May come in handy) under the content.
#
#     - title (string)
#     - url (string)
#     - type (string): show the corresponding icon in front of the title (eg. web, video, github); any icon from the `assets/icons/` folder
#
order: 6
data:
  -
    name: "F-Droid"
    desc: "F-Droid is the go-to FOSS app store for all Android devices."
    tags: ["Open Source", "Android"]
    labels:
      web: "https://f-droid.org/"
    color: "#ffffff"
    favorite: true
  -
    name: "Aurora Store"
    desc: "Aurora Store allows users to download apps directly from the Google Play Store without a Google Account safely."
    tags: [ "Open Source", "Android" ]
    labels:
      web: "https://auroraoss.com/"
    color: "#6B62FF"
    favorite: true
  -
    name: "Obtainium"
    desc: "Obtainium enables you to install & update apps directly from developers, no app stores necessary."
    tags: [ "Open Source", "Android" ]
    labels:
      web: "https://obtainium.imranr.dev/"
    color: "#ebe1ff"
  -
    name: "Exodus Privacy"
    desc: "Analyzes privacy concerns in Android applications. Many iOS applications will use similar trackers, so this is a useful tool to check trackers for applications before downloading."
    tags: [ "Open Source", "Android", "Web" ]
    labels:
      web: "https://exodus-privacy.eu.org/en/"
    color: "#684972"
    favorite: true
  -
    name: "AltStore"
    desc: "AltStore allows iOS users to install IPA files (apps) to their device without the App Store. Apple's restrictions, however, make this a generally limited experience. Europeans can install AltStore PAL for an improved sideloading experience."
    tags: [ "Open Source", "iOS" ]
    labels:
      web: "https://altstore.io/"
    color: "#358389"
