# -----------------------------------------
# PRODUCTION TOOLS
#
# name (string)
# type (string, optional)
# buttons (array)
#
# whiteIcon (boolean):  In case the icon is white (or really light),
#                       this will apply "filter: invert(.75)" when light theme is active
# affil (boolean):      Shows a distinct button with an icon
#
-
  name: "Davinci Resolve Studio"
  type: "Video Production"
  buttons:
    -
      text: "Amazon"
      url: "https://amzn.to/42WfmJn"
      affil: true
    -
      text: "Newegg"
      url: "https://click.linksynergy.com/deeplink?id=3Q9OclTeTTg&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Fp%2F2XW-004F-000D6"
      affil: true      
    -

      text: "Non-affiliate"
      url: "https://www.blackmagicdesign.com/products/davinciresolve"
-
  name: "Synology NAS"
  type: "Collaboration & Files"
  buttons:
    -
      text: "Amazon"
      url: "https://amzn.to/3qYYuo3"
      affil: true
    -
      text: "Newegg"
      url: "https://click.linksynergy.com/deeplink?id=3Q9OclTeTTg&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Fsynology-ds923%2Fp%2F0YH-0064-00009"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.synology.com/en-us/products/DS923+"
-
  name: "Fujifilm X100V"
  type: "Camera"
  buttons:
    -
      text: "Amazon"
      url: "https://amzn.to/49sMVYr"
      affil: true
    -
    text: "Newegg"
      url: "https://click.linksynergy.com/deeplink?id=3Q9OclTeTTg&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Fp%2Fpl%3Fd%3DFujifilm%2BX100V"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://fujifilm-x.com/en-us/products/cameras/x100v/"
-
  name: "DJI Mic 2"
  type: "Lav Mic"
  buttons:
    -
      text: "Amazon"
      url: "https://amzn.to/3Bk0FrI"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.dji.com/mic-2"
-
  name: "Sennheiser Momentum 4"
  type: "Casual Headphones"
  whiteIcon: true
  buttons:
    -
      text: "Amazon"
      url: "https://amzn.to/3VnIAQf"
      affil: true
    -
      text: "Newegg"
      url: "https://click.linksynergy.com/deeplink?id=3Q9OclTeTTg&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Fsennheiser-momentum-4-black-over-the-ear%2Fp%2FN82E16826106921"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.sennheiser-hearing.com/en-US/p/momentum-4-wireless/"
-
  name: "Sennheiser HD600"
  type: "Editing Headphones"
  whiteIcon: true
  buttons:
    -
      text: "Amazon"
      url: "https://amzn.to/3NKvr0A"
      affil: true
    -
      text: "Newegg"
      url: "https://click.linksynergy.com/deeplink?id=3Q9OclTeTTg&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Fsenheiser-hd-600-over-the-ear%2Fp%2F0YC-0037-00001"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.sennheiser-hearing.com/en-US/p/hd-600/"
-
  name: "TubeBuddy"
  type: "Channel Management"
  buttons:
    -
      text: "Affiliate"
      url: "https://www.tubebuddy.com/pricing?a=techlore"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.tubebuddy.com/"
-
  name: "Artlist"
  type: "Stock Audio"
  buttons:
    -
      text: "Affiliate"
      url: "https://artlist.io/artlist-70446/?artlist_aid=techlore_2890"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://artlist.io/"
-
  name: "Hetzner"
  type: "Forum Hosting"
  buttons:
    -
      text: "Affiliate"
      url: "https://hetzner.cloud/?ref=V5WPDBhWKcVF"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.hetzner.com/"
-
  name: "omg.lol"
  type: "Personal Site & Mastodon"
  buttons:
    -
      text: "Affiliate"
      url: "https://home.omg.lol/referred-by/techlore"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://home.omg.lol/"
-
  name: "Parallels"
  type: "OS Virtualization"
  buttons:
    -
      text: "Affiliate"
      url: "https://prf.hn/l/pmnNkkJ"
      affil: true
    -
      text: "Non-affiliate"
      url: "https://www.parallels.com/"
